lane :package do
  ENV['AWS_ACCESS_KEY_ID']     = 'xxxxx'
  ENV['AWS_SECRET_ACCESS_KEY'] = 'xxxxx'
  ENV['AWS_REGION']            = 'us-west-2'
  
  xcodebuild(
    workspace: 'FiveXFive.xcworkspace',
    scheme: 'UITests',
    destination: 'generic/platform=iOS',
    configuration: 'Development',
    derivedDataPath: 'aws',
    xcargs: "GCC_PREPROCESSOR_DEFINITIONS='AWS_UI_TEST' ENABLE_BITCODE=NO build-for-testing"
  )
  
  aws_device_farm_package(
    derrived_data_path: "aws"
  )
  aws_device_farm
end
lane :aws do
  xcodebuild(
    clean: true,
    workspace: 'FiveXFive.xcworkspace',
    scheme: 'UITests',
    destination: 'generic/platform=iOS',
    configuration: 'Development',
    derivedDataPath: 'aws',
    xcargs: "GCC_PREPROCESSOR_DEFINITIONS='AWS_UI_TEST' ENABLE_BITCODE=NO build-for-testing"
  )
  FileUtils.rm_rf '../aws/packages'
  Dir['../aws/Build/Intermediates/CodeCoverage/Products/Development-iphoneos/*.app'].each do |app|
    if app.include? 'Runner'
      FileUtils.mkdir_p '../aws/packages/runner/Payload'
      FileUtils.cp_r app, '../aws/packages/runner/Payload'
      `cd ../aws/packages/runner/; zip -r ../runner.ipa .; cd -`
    else
      FileUtils.mkdir_p '../aws/packages/app/Payload'
      FileUtils.cp_r app, '../aws/packages/app/Payload'
      `cd ../aws/packages/app/; zip -r ../app.ipa .; cd -`
    end
  end

  ENV['AWS_ACCESS_KEY_ID']     = 'xxxxx'
  ENV['AWS_SECRET_ACCESS_KEY'] = 'xxxxx'
  ENV['AWS_REGION']            = 'us-west-2'

  aws_device_farm(
    name:                'fastlane',
    binary_path:         'aws/packages/app.ipa',
    test_binary_path:    'aws/packages/runner.ipa',
    device_pool:         'IOS',
    wait_for_completion: true
  )
end
